# <br><center>**EDA – Web Time Series Forecasting**

In [1]:
import pandas as pd
from IPython.display import display
import gc; gc.enable()

In [2]:
key = pd.read_csv("../datamount/key_1.csv", index_col="Id")
# key2 = pd.read_csv("../datamount/key_2.csv", index_col="Id")
sample_submission = pd.read_csv("../datamount/sample_submission_1.csv", index_col="Id")
# sample_submission2 = pd.read_csv("../datamount/sample_submission_2.csv", index_col="Id")
train = pd.read_csv("../datamount/train_1.csv", index_col="Page")
# train2 = pd.read_csv("../datamount/train_2.csv", index_col="Page")

In [3]:
display(key)
# display(sample_submission)
display(train)

                                                           Page
Id
bf4edcf969af  !vote_en.wikipedia.org_all-access_all-agents_2...
929ed2bf52b9  !vote_en.wikipedia.org_all-access_all-agents_2...
ff29d0f51d5c  !vote_en.wikipedia.org_all-access_all-agents_2...
e98873359be6  !vote_en.wikipedia.org_all-access_all-agents_2...
fa012434263a  !vote_en.wikipedia.org_all-access_all-agents_2...
...                                                         ...
f69747f5ee68  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...
2489963dc503  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...
b0624c909f4c  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...
24a1dfb06c10  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...
add681d54216  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...

[8703780 rows x 1 columns]

,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,2015-07-10,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
Page,,,,,,,,,,,,,,,,,,,,,
2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,24.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,4.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,16.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Underworld_(serie_de_películas)_es.wikipedia.org_all-access_spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.0,12.0,13.0,3.0,5.0,10.0
Resident_Evil:_Capítulo_Final_es.wikipedia.org_all-access_spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Enamorándome_de_Ramón_es.wikipedia.org_all-access_spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hasta_el_último_hombre_es.wikipedia.org_all-access_spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Francisco_el_matemático_(serie_de_televisión_de_2017)_es.wikipedia.org_all-access_spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
list(zip(key.sort_values(by="Page").Page.tolist(), train.sort_index().index.tolist()))[:10]

[('!vote_en.wikipedia.org_all-access_all-agents_2017-01-01',
  '!vote_en.wikipedia.org_all-access_all-agents'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-02',
  '!vote_en.wikipedia.org_all-access_spider'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-03',
  '!vote_en.wikipedia.org_desktop_all-agents'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-04',
  '"Awaken,_My_Love!"_en.wikipedia.org_all-access_all-agents'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-05',
  '"Awaken,_My_Love!"_en.wikipedia.org_all-access_spider'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-06',
  '"Awaken,_My_Love!"_en.wikipedia.org_desktop_all-agents'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-07',
  '"European_Society_for_Clinical_Investigation"_en.wikipedia.org_all-access_all-agents'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-08',
  '"European_Society_for_Clinical_Investigation"_en.wikipedia.org_all-access_spider'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-09',
  '"European_Society_for_Clinical_Investigation"_en.wikipedia.org_desktop_all-agents'),
 ('!vote_en.wikipedia.org_all-access_all-agents_2017-01-10',
  '"Heroes"_(David_Bowie_album)_en.wikipedia.org_all-access_all-agents')]

In [5]:
page = "2NE1_zh.wikipedia.org_all-access_spider"
display(key.query("Page.str.startswith(@page)"))
display(train.loc[page])

                                                           Page
Id
ff8c1aade3de  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
6a4de5b43179  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
559a1ab24535  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
8bd4a4dea5a3  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
fb31ab105824  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
ea2516fbe7dd  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
33e55396b874  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
c88629040f27  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
9f5fc3c0ff56  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
3296d557daaa  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
3b4b37423b5b  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
f53589d0652e  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
b04595c9d119  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
e1fabc9e65b1  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
01fb93ff942a  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
7514325add95  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
5f2b600f06b5  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
1f7da4c6075e  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
7613e704f8d1  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
9063275f9be1  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
5ea1490859c6  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
c845a2416d41  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
65211c9e0d91  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
59ed5f8e75bc  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
3758548c7e95  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
ae2b72a5ba6a  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
e478abddbd37  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
a6dd5e38e68d  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
8e4a33e42146  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
4c89bcd932b9  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
782214ed8366  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
eeea102999b1  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
741e77bfdc08  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
07aa3628f09c  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
56a5bc6a88f6  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
3865fe85114a  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
0c2cae820797  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
32e404068136  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
bfdacc896549  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
86b94fbef4cf  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
ed9ae5ab0590  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
90539e1f19fd  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
4adef3b3308d  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
6aa60ca9a97f  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
fab9ba4bcd2c  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
05a7c95aa18b  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
2fcf46e479e4  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
f02ebed4463a  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
af5f4495c89e  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
f5b0c0b938f9  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
75509e808a00  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
52c0fa00e14f  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
8ee2213cbe75  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
fb422f1edaee  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
0d7a0337af35  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
567d18b36d6f  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
159931d8ebe3  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
9dd37394d132  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
e47fbf61e297  2NE1_zh.wikipedia.org_all-access_spider_2017-0...
97cf6e2d834c  2NE1_zh.wikipedia.org_all-access_spider_2017-0...

2015-07-01    18.0
2015-07-02    11.0
2015-07-03     5.0
2015-07-04    13.0
2015-07-05    14.0
              ...
2016-12-27    20.0
2016-12-28    22.0
2016-12-29    19.0
2016-12-30    18.0
2016-12-31    20.0
Name: 2NE1_zh.wikipedia.org_all-access_spider, Length: 550, dtype: float64

/var/folders/cd/fg135jx14dd1xh9_ft81377c0000gn/T/ipykernel_34780/2144196987.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train = train.reset_index()

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
0,2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
1,2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
2,3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
3,4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Underworld_(serie_de_películas)_es.wikipedia.o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.0,12.0,13.0,3.0,5.0,10.0
145059,Resident_Evil:_Capítulo_Final_es.wikipedia.org...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145060,Enamorándome_de_Ramón_es.wikipedia.org_all-acc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145061,Hasta_el_último_hombre_es.wikipedia.org_all-ac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145062,Francisco_el_matemático_(serie_de_televisión_d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN